//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.01 at 05:10:31 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.han.nl/schemas/messages", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.han.dare2date.service.web.applyregistration.model;
